sequenceDiagram
    participant Przeglądarka
    participant Serwer

    Note right of Przeglądarka: Użytkownik wpisuje notatkę i klika "Save"

    Przeglądarka->>Serwer: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate Serwer
    Serwer-->>Przeglądarka: JSON nowej notatki z ID i datą
    deactivate Serwer

    Note right of Przeglądarka: Strona nie jest przeładowywana
    Note right of Przeglądarka: Nowa notatka jest widoczna natychmiast
