sequenceDiagram
    participant Przeglądarka
    participant Serwer

    Note right of Przeglądarka: Użytkownik wpisuje tekst i klika "Save" 

    Przeglądarka->>Serwer: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate Serwer
    Serwer-->>Przeglądarka: HTML z aktualną listą notatek
    deactivate Serwer

    Note right of Przeglądarka: Przeglądarka przeładowuje stronę /notes

    Przeglądarka->>Serwer: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate Serwer
    Serwer-->>Przeglądarka: Dokument HTML
    deactivate Serwer

    Przeglądarka->>Serwer: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    Serwer-->>Przeglądarka: Plik CSS

    Przeglądarka->>Serwer: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    Serwer-->>Przeglądarka: Plik JavaScript

    Przeglądarka->>Serwer: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate Serwer
    Serwer-->>Przeglądarka: Dane JSON z nową notatką
    deactivate Serwer

    Note right of Przeglądarka: Przeglądarka renderuje zaktualizowaną listę notatek
